/**
 * UI Content Dictionary — EN
 * Source of truth for control names, labels, and other UI text shown to users,
 * shared between sms-web and the mobile apps. Namespaced by surface ("web"/"app")
 * because the two products have different screens, not just different languages.
 *
 * DO NOT hand-edit generated sections without updating the source locale files this
 * was generated from (sms-web/src/locales, apps/kuntalstechfie-app/src/i18n/locales)
 * to keep them in sync, or intentionally diverge and note why.
 */
import { UiContentDictionary } from './content.types';

export const UI_CONTENT_EN: UiContentDictionary = {
  "web": {
    "common": {
      "loading": "Loading...",
      "save": "Save",
      "cancel": "Cancel",
      "delete": "Delete",
      "edit": "Edit",
      "view": "View",
      "add": "Add",
      "search": "Search",
      "filter": "Filter",
      "export": "Export",
      "import": "Import",
      "refresh": "Refresh",
      "back": "Back",
      "next": "Next",
      "previous": "Previous",
      "submit": "Submit",
      "close": "Close",
      "confirm": "Confirm",
      "yes": "Yes",
      "no": "No",
      "success": "Success",
      "error": "Error",
      "warning": "Warning",
      "info": "Info",
      "actions": "Actions",
      "status": "Status",
      "name": "Name",
      "email": "Email",
      "phone": "Phone",
      "address": "Address",
      "date": "Date",
      "time": "Time",
      "description": "Description",
      "remarks": "Remarks",
      "noData": "No data available",
      "select": "Select",
      "all": "All",
      "none": "None",
      "active": "Active",
      "inactive": "Inactive",
      "pending": "Pending",
      "completed": "Completed",
      "high": "High",
      "medium": "Medium",
      "low": "Low",
      "management": "Management"
    },
    "auth": {
      "login": "Login",
      "register": "Register",
      "username": "Username",
      "password": "Password",
      "confirmPassword": "Confirm Password",
      "forgotPassword": "Forgot Password?",
      "rememberMe": "Remember Me",
      "signIn": "Sign in",
      "signingIn": "Signing in...",
      "logout": "Logout",
      "signInToAccount": "Sign in to your account",
      "enterUsername": "Enter your username",
      "enterPassword": "Enter your password",
      "registerCompany": "Register Your Company",
      "registerEntity": "Register School/Tuition/Program",
      "enrollProgram": "Enroll in a Program",
      "dontHaveAccount": "Don't have an account?",
      "loginInstruction": "Login with your registered credentials or register a new account above.",
      "selectAccount": "Select an Account",
      "chooseAccount": "Choose which account you want to access",
      "availableAccounts": "Available Accounts",
      "accountType": {
        "school": "School",
        "learning": "Learning"
      },
      "selectRole": "Select Role",
      "chooseRole": "Choose your role for this session",
      "chooseRoleDescription": "Select the role you want to use for this session",
      "availableRoles": "Available Roles",
      "continue": "Continue",
      "backToAccountSelection": "Back to Account Selection",
      "signedInAs": "Signed in as",
      "invalidCredentials": "Invalid username or password",
      "loginFailed": "Login failed",
      "connectionError": "An error occurred. Please check your connection and try again.",
      "roles": {
        "admin": "Admin",
        "teacher": "Teacher",
        "student": "Student",
        "parent": "Parent",
        "security": "Security"
      },
      "roleDescriptions": {
        "admin": "Manage school operations, staff, and students",
        "teacher": "Manage classes, assignments, and student progress",
        "student": "Access courses, assignments, and grades",
        "parent": "Monitor children's progress and school activities",
        "security": "Manage campus security and bus tracking"
      },
      "continueToDashboard": "Continue to Dashboard",
      "signInToAccess": "Sign in to access your dashboard",
      "admin": "Administrator",
      "teacher": "Teacher",
      "student": "Student",
      "parent": "Parent",
      "security": "Security Guard"
    },
    "navigation": {
      "dashboard": "Dashboard",
      "students": "Students",
      "staff": "Staff",
      "parents": "Parents",
      "attendance": "Attendance",
      "fees": "Fees",
      "tasks": "Tasks",
      "documents": "Documents",
      "results": "Results",
      "history": "History",
      "busTracking": "Bus Tracking",
      "security": "Security",
      "calendar": "Calendar",
      "notifications": "Notifications",
      "settings": "Settings",
      "profile": "Profile",
      "logout": "Logout",
      "messages": "Messages",
      "reports": "Reports"
    },
    "dashboard": {
      "welcome": "Welcome",
      "overview": "Overview",
      "statistics": "Statistics",
      "recentActivity": "Recent Activity",
      "quickActions": "Quick Actions",
      "upcomingEvents": "Upcoming Events",
      "totalStudents": "Total Students",
      "activeTeachers": "Active Teachers",
      "monthlyRevenue": "Monthly Revenue",
      "attendanceRate": "Attendance Rate",
      "currentGPA": "Current GPA",
      "assignmentsDue": "Assignments Due",
      "liveClassesToday": "Live Classes Today",
      "attendancePercentage": "Attendance %",
      "studentsEnrolled": "Students Enrolled",
      "pendingApprovals": "Pending Approvals",
      "activeClasses": "Active Classes",
      "revenueThisMonth": "Revenue This Month"
    },
    "students": {
      "title": "Students",
      "addStudent": "Add Student",
      "editStudent": "Edit Student",
      "deleteStudent": "Delete Student",
      "studentDetails": "Student Details",
      "studentList": "Student List",
      "studentName": "Student Name",
      "studentId": "Student ID",
      "grade": "Grade",
      "class": "Class",
      "section": "Section",
      "parentName": "Parent Name",
      "parentPhone": "Parent Phone",
      "phoneNumber": "Phone Number",
      "email": "Email",
      "address": "Address",
      "dateOfBirth": "Date of Birth",
      "admissionNumber": "Admission Number",
      "admissionDate": "Admission Date",
      "enrollmentDate": "Enrollment Date",
      "gender": "Gender",
      "bloodGroup": "Blood Group",
      "guardianName": "Guardian Name",
      "guardianPhone": "Guardian Phone",
      "emergencyContact": "Emergency Contact",
      "status": "Status",
      "active": "Active",
      "inactive": "Inactive",
      "suspended": "Suspended",
      "graduated": "Graduated",
      "profile": "Profile",
      "viewProfile": "View Profile",
      "rollNumber": "Roll Number"
    },
    "staff": {
      "title": "Staff",
      "addStaff": "Add Staff",
      "editStaff": "Edit Staff",
      "deleteStaff": "Delete Staff",
      "staffDetails": "Staff Details",
      "staffList": "Staff List",
      "staffName": "Staff Name",
      "employeeId": "Employee ID",
      "position": "Position",
      "designation": "Designation",
      "department": "Department",
      "qualification": "Qualification",
      "experience": "Experience",
      "salary": "Salary",
      "hireDate": "Hire Date",
      "joiningDate": "Joining Date",
      "phoneNumber": "Phone Number",
      "email": "Email",
      "address": "Address",
      "status": "Status",
      "active": "Active",
      "inactive": "Inactive"
    },
    "parents": {
      "title": "Parents",
      "addParent": "Add Parent",
      "parentDetails": "Parent Details",
      "parentList": "Parent List",
      "parentName": "Parent Name",
      "parentId": "Parent ID",
      "relationship": "Relationship",
      "children": "Children",
      "phoneNumber": "Phone Number",
      "email": "Email",
      "address": "Address",
      "occupation": "Occupation",
      "emergencyContact": "Emergency Contact"
    },
    "attendance": {
      "title": "Attendance",
      "markAttendance": "Mark Attendance",
      "studentName": "Student Name",
      "studentId": "Student ID",
      "grade": "Grade",
      "section": "Section",
      "date": "Date",
      "class": "Class",
      "subject": "Subject",
      "status": "Status",
      "present": "Present",
      "absent": "Absent",
      "late": "Late",
      "excused": "Excused",
      "checkInTime": "Check In Time",
      "checkOutTime": "Check Out Time",
      "totalStudents": "Total Students",
      "presentCount": "Present",
      "absentCount": "Absent",
      "lateCount": "Late",
      "excusedCount": "Excused",
      "attendancePercentage": "Attendance %",
      "attendanceRate": "Attendance Rate",
      "attendanceReport": "Attendance Report",
      "monthlyReport": "Monthly Report",
      "dailyReport": "Daily Report",
      "exportReport": "Export Report",
      "markedBy": "Marked By",
      "markedAt": "Marked At",
      "remarks": "Remarks",
      "tabs": {
        "daily": "Daily",
        "monthly": "Monthly",
        "reports": "Reports"
      }
    },
    "fees": {
      "title": "Fees",
      "addFee": "Add Fee",
      "editFee": "Edit Fee",
      "studentName": "Student Name",
      "studentId": "Student ID",
      "feeType": "Fee Type",
      "amount": "Amount",
      "dueDate": "Due Date",
      "paymentDate": "Payment Date",
      "status": "Status",
      "paid": "Paid",
      "pending": "Pending",
      "overdue": "Overdue",
      "paymentMethod": "Payment Method",
      "transactionId": "Transaction ID",
      "receiptNumber": "Receipt Number",
      "totalFees": "Total Fees",
      "amountPaid": "Amount Paid",
      "balance": "Balance",
      "collectFees": "Collect Fees",
      "pendingFees": "Pending Fees",
      "paidFees": "Paid Fees",
      "uploadFeeSheet": "Upload Fee Sheet",
      "uploadReceipt": "Upload Receipt",
      "tabs": {
        "feeSheets": "Fee Sheets",
        "receipts": "Receipts"
      }
    },
    "tasks": {
      "title": "Tasks",
      "taskManagement": "Task Management",
      "addTask": "Add Task",
      "editTask": "Edit Task",
      "deleteTask": "Delete Task",
      "taskList": "Task List",
      "taskTitle": "Title",
      "description": "Description",
      "priority": "Priority",
      "status": "Status",
      "dueDate": "Due Date",
      "assignedTo": "Assigned To",
      "createdBy": "Created By",
      "high": "High",
      "medium": "Medium",
      "low": "Low",
      "pending": "Pending",
      "inProgress": "In Progress",
      "completed": "Completed"
    },
    "documents": {
      "title": "Documents",
      "documentManagement": "Document Management",
      "uploadDocument": "Upload Document",
      "documentName": "Document Name",
      "documentType": "Document Type",
      "uploadDate": "Upload Date",
      "uploadedBy": "Uploaded By",
      "download": "Download",
      "view": "View",
      "delete": "Delete"
    },
    "notifications": {
      "title": "Notifications",
      "markAllRead": "Mark All as Read",
      "noNotifications": "No notifications",
      "newNotification": "New Notification",
      "notificationType": "Type",
      "notificationMessage": "Message",
      "notificationTime": "Time",
      "markAsRead": "Mark as Read"
    },
    "settings": {
      "title": "Settings",
      "general": "General",
      "account": "Account",
      "profile": "Profile",
      "accountSettings": "Account Settings",
      "changePassword": "Change Password",
      "currentPassword": "Current Password",
      "newPassword": "New Password",
      "confirmNewPassword": "Confirm New Password",
      "personalInfo": "Personal Information",
      "contactInfo": "Contact Information",
      "preferences": "Preferences",
      "language": "Language",
      "theme": "Theme",
      "notifications": "Notifications",
      "emailNotifications": "Email Notifications",
      "pushNotifications": "Push Notifications",
      "privacy": "Privacy",
      "branding": "School Branding",
      "capacity": "School Capacity",
      "departments": "Departments",
      "classes": "Classes",
      "classSettings": "Class Settings",
      "operational": "Operational Settings",
      "security": "Security Settings"
    },
    "results": {
      "title": "Results",
      "viewResults": "View Results",
      "studentName": "Student Name",
      "grade": "Grade",
      "section": "Section",
      "subject": "Subject",
      "marks": "Marks",
      "percentage": "Percentage",
      "examType": "Exam Type",
      "examDate": "Exam Date"
    },
    "history": {
      "title": "History",
      "activityHistory": "Activity History",
      "recentActivity": "Recent Activity",
      "action": "Action",
      "timestamp": "Timestamp",
      "user": "User"
    },
    "calendar": {
      "title": "Calendar",
      "viewCalendar": "View Calendar",
      "events": "Events",
      "eventTitle": "Event Title",
      "eventDate": "Event Date",
      "eventTime": "Event Time",
      "eventType": "Event Type",
      "location": "Location",
      "description": "Description"
    },
    "busTracking": {
      "title": "Bus Tracking",
      "trackBus": "Track Bus",
      "busNumber": "Bus Number",
      "driverName": "Driver Name",
      "route": "Route",
      "currentLocation": "Current Location",
      "estimatedArrival": "Estimated Arrival",
      "status": "Status"
    },
    "security": {
      "title": "Security",
      "securityManagement": "Security Management",
      "visitorLog": "Visitor Log",
      "incidentReport": "Incident Report",
      "cameraMonitoring": "Camera Monitoring"
    },
    "teacher": {
      "attendance": "Teacher Attendance",
      "marks": "Grade Submissions",
      "classes": "My Classes",
      "schedule": "Schedule",
      "resources": "Resources",
      "messages": "Messages",
      "profile": "Teacher Profile",
      "progress": "Student Progress"
    },
    "student": {
      "liveClasses": "Live Classes",
      "courses": "Courses",
      "assignments": "Assignments",
      "grades": "Grades",
      "certificates": "Certificates",
      "materials": "Study Materials",
      "profile": "Student Profile"
    },
    "parent": {
      "progress": "Children Progress",
      "attendance": "Parent Attendance",
      "assignments": "Assignments",
      "events": "School Events",
      "messages": "Parent Messages"
    },
    "registration": {
      "coaching": {
        "title": "Register Coaching",
        "description": "Enter coaching center name and contact details",
        "additionalDetails": "Additional Details",
        "additionalDetailsDesc": "Add address, website, and other information",
        "profile": "Coaching Profile",
        "profileDesc": "Add competitive exams and other details",
        "location": "Location",
        "locationDesc": "Add location details and coordinates (optional)",
        "subscription": "Subscription",
        "subscriptionDesc": "Select subscription plan",
        "adminDetails": "Admin Details",
        "adminDetailsDesc": "Add super admin user details",
        "payment": "Payment:",
        "paymentDesc": "Process payment for subscription",
        "approve": "Approve",
        "approveDesc": "Review and approve registration",
        "activate": "Activate",
        "activateDesc": "Activate the coaching center account",
        "nameRequired": "Coaching center name is required",
        "contactPersonRequired": "Contact person name is required",
        "contactEmailRequired": "Contact email is required",
        "validEmailRequired": "Please enter a valid email address",
        "contactPhoneRequired": "Contact phone is required",
        "locationSearchRequired": "Please search for location details using the pincode before proceeding",
        "planRequired": "Please select a subscription plan",
        "startDateRequired": "Please select a start date",
        "endDateRequired": "Please select an end date",
        "adminUsernameRequired": "Admin username is required",
        "adminPasswordRequired": "Admin password is required",
        "passwordsDoNotMatch": "Passwords do not match",
        "paymentRequired": "Please complete the payment or select \"Pay Later\"",
        "completePreviousSteps": "Please complete the previous steps and select a subscription plan",
        "namePlaceholder": "Enter coaching center name",
        "contactPersonPlaceholder": "Enter contact person name",
        "contactEmailPlaceholder": "Enter contact email",
        "contactPhonePlaceholder": "Enter contact phone",
        "addressPlaceholder": "Enter address",
        "shortNamePlaceholder": "Enter short name",
        "usernamePlaceholder": "Username for super admin",
        "plan": "Plan:",
        "selectedPlan": "Selected Plan",
        "processingPayment": "Processing...",
        "paymentCompleted": "Payment Completed",
        "payViaRazorpay": "Pay via Razorpay",
        "completed": "Completed",
        "pending": "Pending"
      },
      "tuition": {
        "title": "Register Tuition",
        "description": "Enter tuition center name and contact details",
        "additionalDetails": "Additional Details",
        "additionalDetailsDesc": "Add address, website, and other information",
        "profile": "Tuition Profile",
        "profileDesc": "Add subjects and other details",
        "location": "Location",
        "locationDesc": "Add location details and coordinates (optional)",
        "subscription": "Subscription",
        "subscriptionDesc": "Select subscription plan",
        "adminDetails": "Admin Details",
        "adminDetailsDesc": "Add super admin user details",
        "payment": "Payment",
        "paymentDesc": "Process payment for subscription",
        "approve": "Approve",
        "approveDesc": "Review and approve registration",
        "activate": "Activate",
        "activateDesc": "Activate the tuition center account",
        "nameRequired": "Tuition center name is required",
        "contactPersonRequired": "Contact person name is required",
        "contactEmailRequired": "Contact email is required",
        "validEmailRequired": "Please enter a valid email address",
        "contactPhoneRequired": "Contact phone is required",
        "locationSearchRequired": "Please search for location details using the pincode before proceeding",
        "planRequired": "Please select a subscription plan",
        "startDateRequired": "Please select a start date",
        "endDateRequired": "Please select an end date",
        "adminUsernameRequired": "Admin username is required",
        "adminPasswordRequired": "Admin password is required",
        "passwordsDoNotMatch": "Passwords do not match",
        "paymentRequired": "Please complete the payment or select \"Pay Later\"",
        "completePreviousSteps": "Please complete the previous steps and select a subscription plan"
      }
    },
    "errors": {
      "required": "This field is required",
      "invalidEmail": "Invalid email address",
      "invalidPhone": "Invalid phone number",
      "passwordMismatch": "Passwords do not match",
      "passwordTooShort": "Password must be at least 8 characters",
      "somethingWentWrong": "Something went wrong. Please try again.",
      "networkError": "Network error. Please check your connection.",
      "unauthorized": "Unauthorized access",
      "forbidden": "Access forbidden",
      "notFound": "Page not found",
      "serverError": "Server error. Please try again later.",
      "failedToLoad": "Failed to load",
      "failedToLoadCompanies": "Failed to load companies",
      "failedToLoadSchools": "Failed to load schools",
      "failedToLoadTuitionCenters": "Failed to load tuition centers",
      "failedToLoadCoachingCenters": "Failed to load coaching centers",
      "failedToLoadUsers": "Failed to load users",
      "pleaseSelectCompany": "Please select a company first",
      "unknownCompany": "Unknown Company",
      "unknown": "Unknown",
      "editFunctionalityComingSoon": "Edit functionality for this user type coming soon",
      "addUserFunctionalityComingSoon": "Add user functionality coming soon",
      "failedToApprove": "Failed to approve",
      "failedToReject": "Failed to reject",
      "failedToDelete": "Failed to delete",
      "failedToUpdate": "Failed to update",
      "failedToRegister": "Failed to register",
      "failedToCompleteRegistration": "Failed to complete registration",
      "failedToGetId": "Failed to get ID from registration response",
      "paymentCancelled": "Payment was cancelled",
      "failedToInitiatePayment": "Failed to initiate payment",
      "paymentVerificationFailed": "Payment verification failed",
      "failedToRegisterEntity": "Failed to register entity"
    },
    "messages": {
      "title": "Messages",
      "compose": "Compose",
      "inbox": "Inbox",
      "sent": "Sent",
      "draft": "Draft",
      "subject": "Subject",
      "recipient": "Recipient",
      "priority": "Priority",
      "high": "High",
      "medium": "Medium",
      "low": "Low",
      "message": "Message",
      "send": "Send",
      "reply": "Reply",
      "forward": "Forward"
    },
    "header": {
      "title": "BrightLearn",
      "subtitle": "School Management System",
      "systemTitle": "SMS Management System",
      "logout": "Logout",
      "settings": "Settings",
      "notifications": "Notifications",
      "superAdmin": "Super Admin",
      "parentAdmin": "Parent Admin"
    },
    "companyUser": {
      "title": "Company Management Hub",
      "welcome": "Welcome",
      "active": "Active",
      "lastLogin": "Last Login",
      "whatWouldYouLikeToDo": "What would you like to do?",
      "selectSection": "Select a section below to manage your organizations and access key features",
      "recentUpdates": "Recent Updates",
      "needHelp": "Need help? Contact support at",
      "navigation": {
        "dashboard": {
          "title": "Company Dashboard",
          "description": "View all assigned organizations, statistics, and activities"
        },
        "schools": {
          "title": "Schools Management",
          "description": "Manage schools, classes, staff, and student enrollment"
        },
        "coaching": {
          "title": "Coaching Centers",
          "description": "Oversee coaching centers and competitive exam programs"
        },
        "tuition": {
          "title": "Tuition Management",
          "description": "Manage tuition services and personalized training"
        },
        "analytics": {
          "title": "Analytics & Reports",
          "description": "View detailed reports and performance analytics"
        },
        "settings": {
          "title": "Settings & Configuration",
          "description": "Manage account settings, permissions, and preferences"
        }
      },
      "stats": {
        "organizations": "Organizations",
        "totalStudents": "Total Students",
        "totalStaff": "Total Staff",
        "notifications": "Notifications"
      },
      "recentActivities": {
        "newEnrollment": "New student enrollment",
        "attendanceReport": "Staff attendance report",
        "scheduleUpdated": "Class schedule updated"
      },
      "badges": {
        "popular": "Popular",
        "schools": "Schools",
        "coaching": "Coaching",
        "tuition": "Tuition",
        "analytics": "Analytics",
        "settings": "Settings"
      },
      "actions": {
        "explore": "Explore",
        "logout": "Logout"
      }
    },
    "toasts": {
      "success": {
        "coachingApproved": "Coaching approved successfully",
        "coachingRejected": "Coaching rejected successfully",
        "coachingDeleted": "Coaching deleted successfully",
        "coachingUpdated": "Coaching updated successfully",
        "coachingRegistrationCompleted": "Coaching registration completed successfully.",
        "tuitionApproved": "Tuition approved successfully",
        "tuitionRejected": "Tuition rejected successfully",
        "tuitionDeleted": "Tuition deleted successfully",
        "tuitionUpdated": "Tuition updated successfully",
        "tuitionRegistrationCompleted": "Tuition registration completed successfully.",
        "schoolApproved": "School approved successfully",
        "schoolRejected": "School rejected successfully",
        "schoolDeleted": "School deleted successfully",
        "schoolUpdated": "School updated successfully",
        "schoolActivated": "School activated successfully",
        "schoolDeactivated": "School deactivated successfully",
        "schoolRegistrationCompleted": "School registration completed successfully.",
        "paymentCompleted": "Payment completed successfully!"
      },
      "error": {
        "failedToLoadCoaching": "Failed to load coachings",
        "failedToLoadTuition": "Failed to load tuitions"
      }
    },
    "userManagement": {
      "title": "User Management",
      "description": "Manage users for companies, schools, tuition, and coaching providers.",
      "selectCompany": "Select Company:",
      "selectCompanyPlaceholder": "Select a company...",
      "loadingCompanies": "Loading companies...",
      "noCompaniesAvailable": "No companies available",
      "companyUsers": "Company Users",
      "schoolUsers": "School Users",
      "tuitionUsers": "Tuition Users",
      "coachingUsers": "Coaching Users",
      "users": "Users",
      "selectSchool": "Select School:",
      "selectTuition": "Select Tuition:",
      "selectCoaching": "Select Coaching:",
      "selectSchoolPlaceholder": "Select School...",
      "selectTuitionPlaceholder": "Select Tuition Center...",
      "selectCoachingPlaceholder": "Select Coaching Center...",
      "allSchools": "All Schools",
      "allTuitionCenters": "All Tuition Centers",
      "allCoachingCenters": "All Coaching Centers",
      "addUser": "Add User",
      "addStudent": "Add Student",
      "staff": "Staff",
      "students": "Students",
      "for": "for",
      "companyAdmin": "Company Admin",
      "companyUser": "Company User",
      "active": "Active",
      "inactive": "Inactive",
      "editUser": "Edit user",
      "viewDetails": "View Details",
      "edit": "Edit",
      "approve": "Approve",
      "reject": "Reject",
      "delete": "Delete",
      "saving": "Saving...",
      "saveChanges": "Save Changes",
      "selectSchoolLabel": "Select School:",
      "selectTuitionLabel": "Select Tuition:",
      "selectCoachingLabel": "Select Coaching:",
      "searchPlaceholder": "Search users by name, email, or username...",
      "pleaseSelectCompanyToView": "Please select a company to view users",
      "loadingUsers": "Loading users...",
      "usersFound": "user(s) found",
      "studentsFound": "student(s) found",
      "noUsersFound": "No users found matching",
      "noUsersForEntity": "No users found for this entity",
      "name": "NAME",
      "email": "EMAIL",
      "username": "USERNAME",
      "role": "ROLE",
      "status": "STATUS",
      "actions": "ACTIONS",
      "nA": "N/A",
      "noSchoolsRegistered": "No Schools Registered",
      "noTuitionsRegistered": "No Tuition Centers Registered",
      "noCoachingsRegistered": "No Coaching Centers Registered",
      "registerSchoolFirst": "Please register a school for this company first before managing school users.",
      "registerTuitionFirst": "Please register a tuition center for this company first before managing tuition users.",
      "registerCoachingFirst": "Please register a coaching center for this company first before managing coaching users.",
      "registerSchool": "Register a School",
      "registerTuition": "Register a Tuition Center",
      "registerCoaching": "Register a Coaching Center",
      "schoolsAvailable": "school(s) available",
      "tuitionsAvailable": "tuition center(s) available",
      "coachingsAvailable": "coaching center(s) available"
    },
    "entityManagement": {
      "coachingDetails": "Coaching Details",
      "editCoaching": "Edit Coaching",
      "tuitionDetails": "Tuition Details",
      "editTuition": "Edit Tuition",
      "approved": "Approved",
      "pending": "Pending",
      "active": "Active",
      "inactive": "Inactive"
    },
    "modules": {
      "company": {
        "title": "Company Management",
        "description": "Manage companies and organizations",
        "features": {
          "list": {
            "title": "Company List",
            "description": "View and manage all companies",
            "selectors": {
              "selectCompany": "Select Company:",
              "allCompanies": "All Companies"
            },
            "table": {
              "headers": {
                "companyName": "Company Name",
                "companyId": "Company ID",
                "status": "Status",
                "createdAt": "Created At",
                "actions": "Actions"
              }
            },
            "actions": {
              "list": "List Companies",
              "add": "Add Company",
              "edit": "Edit Company",
              "delete": "Delete Company",
              "view": "View Details",
              "export": "Export Companies",
              "import": "Import Companies",
              "refresh": "Refresh List",
              "search": "Search Companies",
              "filter": "Filter Companies"
            },
            "filters": {
              "all": "All Companies",
              "active": "Active Only",
              "inactive": "Inactive Only",
              "pending": "Pending Approval"
            }
          },
          "users": {
            "title": "Company Users",
            "description": "Manage user accounts",
            "table": {
              "headers": {
                "name": "Name",
                "email": "Email",
                "username": "Username",
                "role": "Role",
                "status": "Status",
                "lastLogin": "Last Login",
                "actions": "Actions"
              }
            },
            "actions": {
              "list": "List Users",
              "add": "Add User",
              "edit": "Edit User",
              "delete": "Delete User",
              "view": "View User",
              "export": "Export Users",
              "import": "Import Users",
              "search": "Search Users",
              "approve": "Approve User",
              "reject": "Reject User",
              "suspend": "Suspend User",
              "activate": "Activate User",
              "resetPassword": "Reset Password",
              "assignRole": "Assign Role"
            },
            "filters": {
              "all": "All Users",
              "active": "Active Only",
              "inactive": "Inactive Only",
              "pending": "Pending Approval",
              "suspended": "Suspended"
            },
            "bulk": {
              "select": "Select Users",
              "delete": "Delete Selected",
              "export": "Export Selected",
              "approve": "Approve Selected",
              "reject": "Reject Selected"
            }
          }
        }
      },
      "school": {
        "title": "School Management",
        "description": "Manage schools and educational institutions",
        "features": {
          "list": {
            "title": "School List",
            "selectors": {
              "selectSchool": "Select School:",
              "allSchools": "All Schools"
            },
            "actions": {
              "list": "List Schools",
              "add": "Add School",
              "edit": "Edit School",
              "delete": "Delete School",
              "view": "View School",
              "export": "Export Schools",
              "import": "Import Schools",
              "approve": "Approve School",
              "reject": "Reject School"
            }
          },
          "users": {
            "title": "School Users",
            "userTypes": {
              "staff": "Staff",
              "students": "Students",
              "teachers": "Teachers",
              "parents": "Parents"
            },
            "table": {
              "headers": {
                "name": "Name",
                "email": "Email",
                "username": "Username",
                "userType": "User Type",
                "status": "Status",
                "enrollmentDate": "Enrollment Date",
                "actions": "Actions"
              }
            },
            "actions": {
              "list": "List Users",
              "add": "Add User",
              "edit": "Edit User",
              "delete": "Delete User",
              "view": "View User",
              "export": "Export Users",
              "import": "Import Users",
              "approve": "Approve User",
              "reject": "Reject User",
              "transfer": "Transfer User",
              "promote": "Promote User"
            },
            "count": {
              "usersFound": "{{count}} user(s) found",
              "studentsFound": "{{count}} student(s) found"
            }
          },
          "students": {
            "title": "Student Management",
            "actions": {
              "list": "List Students",
              "add": "Add Student",
              "edit": "Edit Student",
              "view": "View Student",
              "delete": "Delete Student",
              "export": "Export Students",
              "import": "Import Students",
              "enroll": "Enroll Student",
              "transfer": "Transfer Student",
              "promote": "Promote Student",
              "graduate": "Graduate Student",
              "suspend": "Suspend Student"
            },
            "bulk": {
              "enroll": "Bulk Enroll",
              "promote": "Bulk Promote",
              "export": "Bulk Export"
            }
          },
          "staff": {
            "title": "Staff Management",
            "actions": {
              "list": "List Staff",
              "add": "Add Staff",
              "edit": "Edit Staff",
              "view": "View Staff",
              "delete": "Delete Staff",
              "export": "Export Staff",
              "import": "Import Staff",
              "assign": "Assign Role",
              "transfer": "Transfer Staff"
            }
          },
          "attendance": {
            "title": "Attendance Management",
            "actions": {
              "mark": "Mark Attendance",
              "view": "View Attendance",
              "edit": "Edit Attendance",
              "export": "Export Attendance",
              "report": "Generate Report"
            }
          },
          "fees": {
            "title": "Fee Management",
            "actions": {
              "list": "List Fees",
              "collect": "Collect Fee",
              "view": "View Fee",
              "export": "Export Fees",
              "generateReceipt": "Generate Receipt",
              "sendReminder": "Send Reminder"
            }
          }
        }
      },
      "tuition": {
        "title": "Tuition Management",
        "description": "Manage tuition centers and services",
        "features": {
          "list": {
            "title": "Tuition Centers",
            "selectors": {
              "selectTuition": "Select Tuition:",
              "allTuitions": "All Tuition Centers"
            },
            "actions": {
              "list": "List Tuition Centers",
              "add": "Add Tuition Center",
              "edit": "Edit Tuition Center",
              "delete": "Delete Tuition Center",
              "view": "View Details",
              "export": "Export Tuition Centers",
              "approve": "Approve Tuition Center"
            }
          },
          "users": {
            "title": "Tuition Users",
            "userTypes": {
              "staff": "Staff",
              "students": "Students",
              "tutors": "Tutors"
            },
            "actions": {
              "list": "List Users",
              "add": "Add User",
              "edit": "Edit User",
              "delete": "Delete User",
              "view": "View User",
              "export": "Export Users",
              "import": "Import Users",
              "assign": "Assign Tutor"
            }
          },
          "sessions": {
            "title": "Session Management",
            "actions": {
              "list": "List Sessions",
              "schedule": "Schedule Session",
              "cancel": "Cancel Session",
              "reschedule": "Reschedule Session",
              "export": "Export Sessions"
            }
          }
        }
      },
      "coaching": {
        "title": "Coaching Management",
        "description": "Manage coaching centers and competitive exam programs",
        "features": {
          "list": {
            "title": "Coaching Centers",
            "selectors": {
              "selectCoaching": "Select Coaching:",
              "allCoachings": "All Coaching Centers"
            },
            "actions": {
              "list": "List Coaching Centers",
              "add": "Add Coaching Center",
              "edit": "Edit Coaching Center",
              "delete": "Delete Coaching Center",
              "view": "View Details",
              "export": "Export Coaching Centers",
              "approve": "Approve Coaching Center"
            }
          },
          "users": {
            "title": "Coaching Users",
            "userTypes": {
              "staff": "Staff",
              "students": "Students",
              "instructors": "Instructors"
            },
            "actions": {
              "list": "List Users",
              "add": "Add User",
              "edit": "Edit User",
              "delete": "Delete User",
              "view": "View User",
              "export": "Export Users",
              "import": "Import Users",
              "enroll": "Enroll Student"
            }
          },
          "batches": {
            "title": "Batch Management",
            "actions": {
              "list": "List Batches",
              "create": "Create Batch",
              "edit": "Edit Batch",
              "delete": "Delete Batch",
              "assign": "Assign Students",
              "export": "Export Batches"
            }
          },
          "exams": {
            "title": "Exam Management",
            "actions": {
              "list": "List Exams",
              "schedule": "Schedule Exam",
              "conduct": "Conduct Exam",
              "evaluate": "Evaluate Exam",
              "publish": "Publish Results",
              "export": "Export Results"
            }
          }
        }
      }
    }
  },
  "app": {
    "app": {
      "shortName": "skoorrerr",
      "companyName": "skoorrerr"
    },
    "splash": {
      "rolePill": "Company Admin",
      "headlineLine1": "Manage your network,",
      "headlineLine2": "all in one place.",
      "tagline": "Organizations, teams, tasks, and subscriptions — powered by skoorrerr.",
      "versionSuffix": "v1.0",
      "poweredBy": "skoorrerr · Company Portal v1.0"
    },
    "languages": {
      "en": "English",
      "hi": "हिन्दी",
      "es": "Español",
      "choose": "Language"
    },
    "common": {
      "loading": "Loading...",
      "error": "An error occurred",
      "back": "Back",
      "viewAll": "View all",
      "open": "Open",
      "active": "Active",
      "inactive": "Inactive",
      "pending": "Pending",
      "approved": "Approved",
      "rejected": "Rejected",
      "success": "Success"
    },
    "login": {
      "welcome": "Welcome back",
      "subtitle": "Sign in to your company account",
      "brandTagline": "Smart school management for growing networks.",
      "companyPortal": "Company portal",
      "devMenu": "Developer menu",
      "emailPlaceholder": "Email or username",
      "passwordPlaceholder": "Password",
      "forgotPassword": "Forgot password?",
      "loginButton": "Log in",
      "newHere": "New here?",
      "registerCompany": "Register your company"
    },
    "errors": {
      "usernameRequired": "Please enter your username or email.",
      "passwordRequired": "Please enter your password.",
      "loginFailed": "Login failed",
      "loginInvalid": "Invalid username or password."
    },
    "changePassword": {
      "title": "Change password",
      "description": "Enter your current password and a new secure password.",
      "currentPassword": "Current password",
      "newPassword": "New password",
      "confirmPassword": "Confirm new password",
      "button": "Update password",
      "mismatch": "New passwords do not match.",
      "successTitle": "Password updated",
      "successMessage": "Your password has been changed successfully.",
      "failed": "Could not change password."
    },
    "dashboard": {
      "welcome": "Welcome",
      "roleLabel": "Company Admin",
      "home": "Home",
      "profile": "Profile",
      "modules": "Modules",
      "today": "Today",
      "greetMorning": "Good morning",
      "greetAfternoon": "Good afternoon",
      "greetEvening": "Good evening",
      "daySummaryLabel": "Overview",
      "orgsUnit": "organizations",
      "tasksSummary": "{{tasks}} · stay on top",
      "primaryCta": "View organizations",
      "yourShortcuts": "Quick access",
      "toolsHeading": "Management tools",
      "openPill": "Open",
      "notificationsHint": "Notifications",
      "passCardTitle": "Company portal",
      "passCardSub": "Tap shortcuts below",
      "peekCardTitle": "This month",
      "peekCardSub": "Track tasks and approvals",
      "personalInfo": "Personal info",
      "accountInfo": "Account",
      "labelName": "Name",
      "labelEmail": "Email",
      "labelRole": "Role",
      "notSet": "—",
      "signOut": "Sign out",
      "statOrgs": "Total organizations",
      "statUsers": "Company users",
      "statStudents": "Total students",
      "statClasses": "Total classes",
      "statTasks": "Pending tasks",
      "statApprovals": "Pending approvals"
    },
    "modules": {
      "organizations": "Organizations",
      "tasks": "Tasks",
      "teams": "Teams",
      "users": "Users",
      "roleManagement": "Role Management",
      "masterData": "Master Data",
      "notifications": "Notifications",
      "settings": "Settings",
      "subscription": "Subscription",
      "approvals": "Approvals",
      "sales": "Sales",
      "operations": "Operations",
      "schoolManagement": "School Management",
      "tuitionManagement": "Tuition Management",
      "coachingManagement": "Coaching Management",
      "inbox": "Inbox",
      "helpCenter": "Help Center",
      "parentManagement": "Parent Management",
      "companyManagement": "Company Management",
      "deviceApprovals": "Device Approvals",
      "orders": "Orders & Payments",
      "taskTemplates": "Task Templates",
      "menuManagement": "Menu Management"
    },
    "moduleDesc": {
      "organizations": "Schools, tuitions & coachings",
      "tasks": "Pending tasks & follow-ups",
      "teams": "Manage your company teams",
      "users": "Company user accounts",
      "roleManagement": "Roles, permissions & RBAC",
      "masterData": "All reference & geographic data",
      "notifications": "Alerts and company messages",
      "settings": "Company profile & configuration",
      "subscription": "Plans, modules & billing",
      "approvals": "Pending entity approvals",
      "sales": "Sales pipeline & leads",
      "operations": "Operational overview",
      "schoolManagement": "Manage registered schools",
      "tuitionManagement": "Manage tuition providers",
      "coachingManagement": "Manage coaching centers",
      "inbox": "Internal company messages",
      "helpCenter": "Support and FAQs",
      "parentManagement": "School, tuition & coaching parents",
      "companyManagement": "Manage registered companies",
      "deviceApprovals": "Approve mobile device logins",
      "orders": "Orders, payments & billing",
      "taskTemplates": "Reusable task templates",
      "menuManagement": "Dashboard menu visibility"
    },
    "organizations": {
      "title": "Organizations",
      "schools": "Schools",
      "tuitions": "Tuitions",
      "coachings": "Coachings",
      "all": "All",
      "search": "Search organizations...",
      "noData": "No organizations found.",
      "type": "Type",
      "status": "Status",
      "createdAt": "Created"
    },
    "tasks": {
      "title": "Tasks",
      "noData": "No tasks found.",
      "priority": "Priority",
      "dueDate": "Due date",
      "assignee": "Assignee",
      "high": "High",
      "medium": "Medium",
      "low": "Low",
      "open": "Open",
      "inProgress": "In Progress",
      "completed": "Completed",
      "noDescription": "No description provided.",
      "updateStatus": "Update status",
      "notFound": "Task not found.",
      "addTask": "Add task",
      "createTask": "Create task",
      "titleLabel": "Title",
      "descriptionLabel": "Description",
      "titleRequired": "Task title is required.",
      "createdTitle": "Task created",
      "createdMessage": "The task was created successfully.",
      "createFailed": "Could not create task.",
      "delete": "Delete",
      "deleteTask": "Delete task",
      "deleteFailed": "Could not delete task.",
      "reassign": "Reassign task",
      "reassignFailed": "Could not reassign task.",
      "noUsers": "No users available to assign.",
      "pickAssignee": "Select assignee",
      "templatesTitle": "Task templates",
      "templatesSubtitle": "Master task library",
      "addTemplate": "Add template",
      "noTemplates": "No templates yet.",
      "deleteTemplate": "Delete template"
    },
    "teams": {
      "title": "Teams",
      "noData": "No teams found.",
      "members": "members",
      "lead": "Team lead",
      "noMembers": "No team members found.",
      "addTeam": "Add team",
      "editTeam": "Edit team",
      "nameLabel": "Team name",
      "descriptionLabel": "Description",
      "save": "Save team",
      "savedTitle": "Team saved",
      "savedMessage": "Team details were saved successfully.",
      "saveFailed": "Could not save team.",
      "loadFailed": "Could not load team.",
      "nameRequired": "Team name is required.",
      "addMember": "Add member",
      "removeMember": "Remove member",
      "remove": "Remove",
      "selectMember": "Select member",
      "deleteTeam": "Delete team",
      "delete": "Delete",
      "deleteFailed": "Could not delete team.",
      "addMemberFailed": "Could not add member.",
      "removeMemberFailed": "Could not remove member.",
      "loadUsersFailed": "Could not load users."
    },
    "users": {
      "title": "Users",
      "noData": "No users found.",
      "search": "Search users...",
      "role": "Role",
      "status": "Status",
      "username": "Username",
      "email": "Email",
      "phone": "Phone",
      "roles": "Roles",
      "addUser": "Add user",
      "editUser": "Edit user",
      "firstName": "First name",
      "lastName": "Last name",
      "password": "Password",
      "activeAccount": "Active account",
      "save": "Save user",
      "savedTitle": "User saved",
      "savedMessage": "User details were saved successfully.",
      "saveFailed": "Could not save user.",
      "loadFailed": "Could not load user.",
      "requiredFields": "First name and email are required.",
      "createRequired": "Username and password are required for new users.",
      "activate": "Activate account",
      "deactivate": "Deactivate account",
      "actionFailed": "Action failed.",
      "groups": "Groups",
      "deleteUser": "Delete user",
      "delete": "Delete",
      "deleteFailed": "Could not delete user."
    },
    "roleManagement": {
      "title": "Role Management",
      "roles": "Roles",
      "permissions": "Permissions",
      "noData": "No roles defined.",
      "createRole": "Create role",
      "rolesTab": "Roles",
      "groupsTab": "Groups",
      "noGroups": "No groups found.",
      "createGroup": "Create group",
      "nameLabel": "Name",
      "descriptionLabel": "Description",
      "save": "Save",
      "savedTitle": "Saved",
      "savedMessage": "Record saved successfully.",
      "saveFailed": "Could not save.",
      "nameRequired": "Name is required.",
      "deleteRole": "Delete role",
      "deleteGroup": "Delete group",
      "delete": "Delete",
      "deleteFailed": "Could not delete."
    },
    "masterData": {
      "title": "Master Data",
      "subtitle": "Manage all reference data and master records",
      "searchPlaceholder": "Search modules…",
      "searchRecords": "Search records…",
      "allModules": "All",
      "noModules": "No modules match your search.",
      "unknownSection": "Unknown master data section.",
      "loadFailed": "Failed to load master data.",
      "grades": "Grades",
      "sections": "Sections",
      "categories": "Categories",
      "noData": "No data found.",
      "addItem": "Add item",
      "editItem": "Edit item",
      "nameLabel": "Name",
      "nameEn": "Name (English)",
      "nameHi": "Name (Hindi)",
      "descriptionEn": "Description (English)",
      "descriptionHi": "Description (Hindi)",
      "code": "Code",
      "isoCode": "ISO Code",
      "symbol": "Symbol",
      "category": "Category",
      "country": "Country",
      "circle": "Circle",
      "state": "State",
      "district": "District",
      "city": "City",
      "town": "Town",
      "subject": "Subject",
      "book": "Book",
      "placeCode": "Place code",
      "stateCode": "State code",
      "districtCode": "District code",
      "cityCode": "City code",
      "townCode": "Town code",
      "languageName": "Language name",
      "languageCode": "Language code",
      "active": "Active",
      "save": "Save",
      "savedTitle": "Saved",
      "savedMessage": "Master data saved successfully.",
      "saveFailed": "Could not save.",
      "nameRequired": "English name is required.",
      "languageRequired": "Language name and code are required.",
      "subjectBookRequired": "Subject and book are required.",
      "countryRequired": "Country is required.",
      "circleRequired": "Circle is required.",
      "districtRequired": "Name, district code, and state are required.",
      "townRequired": "Name, town code, and district are required.",
      "placeRequired": "Name, place code, and town are required.",
      "deleteItem": "Delete item",
      "delete": "Delete",
      "deleteFailed": "Could not delete."
    },
    "notifications": {
      "title": "Notifications",
      "noData": "No notifications.",
      "markAllRead": "Mark all read",
      "allTab": "All",
      "unreadTab": "Unread",
      "deleteTitle": "Delete notification",
      "delete": "Delete"
    },
    "settings": {
      "title": "Settings",
      "companyProfile": "Company profile",
      "contactInfo": "Contact info",
      "preferences": "Preferences",
      "security": "Security",
      "about": "About",
      "editProfile": "Edit company profile",
      "companyName": "Company name",
      "shortName": "Short name",
      "email": "Email",
      "phone": "Phone",
      "address": "Address",
      "save": "Save changes",
      "savedTitle": "Profile updated",
      "savedMessage": "Company profile was saved successfully.",
      "saveFailed": "Could not save profile.",
      "nameRequired": "Company name is required."
    },
    "subscription": {
      "title": "Subscription",
      "currentPlan": "Current plan",
      "expiresOn": "Expires on",
      "modules": "Included modules",
      "upgrade": "Upgrade plan",
      "noData": "No subscription data.",
      "renew": "Renew",
      "cancel": "Cancel",
      "invoices": "Invoices",
      "noInvoices": "No invoices found.",
      "actionFailed": "Subscription action failed."
    },
    "approvals": {
      "title": "Approvals",
      "pending": "Pending",
      "approved": "Approved",
      "rejected": "Rejected",
      "noData": "No pending approvals.",
      "approve": "Approve",
      "reject": "Reject"
    },
    "deviceApprovals": {
      "title": "Device Approvals",
      "subtitle": "Pending mobile device authorizations",
      "noData": "No pending devices.",
      "approveTitle": "Approve device",
      "revokeTitle": "Revoke device",
      "revoke": "Revoke"
    },
    "pendingApproval": {
      "title": "Waiting for approval",
      "subtitleNew": "A company admin needs to approve this device before you can sign in.",
      "subtitleReplacement": "This device will replace one of your existing approved devices once an admin approves it.",
      "checking": "Checking approval status…",
      "checkNow": "Check now",
      "backToLogin": "Back to login",
      "approved": "Device approved! Signing you in…"
    },
    "sessionLimit": {
      "title": "Already signed in elsewhere",
      "subtitle": "Sign out of one of these to continue on this device.",
      "signOut": "Sign out & continue",
      "signingOut": "Signing out…",
      "cancel": "Cancel"
    },
    "parentManagement": {
      "title": "Parent Management",
      "subtitle": "Parents across schools, tuitions & coachings",
      "noData": "No parents found.",
      "approveTitle": "Approve parent"
    },
    "companyManagement": {
      "title": "Company Management",
      "subtitle": "Registered companies in the network",
      "noData": "No companies found."
    },
    "orders": {
      "title": "Orders & Payments",
      "subtitle": "Billing and payment records",
      "noData": "No orders found.",
      "markPaid": "Mark paid",
      "markPaidTitle": "Mark order as paid"
    },
    "inbox": {
      "inboxTab": "Inbox",
      "sentTab": "Sent",
      "compose": "Compose message",
      "recipients": "Recipients",
      "subject": "Subject",
      "body": "Message",
      "send": "Send",
      "composeRequired": "Subject, message, and at least one recipient are required.",
      "sentTitle": "Message sent",
      "sentMessage": "Your message was sent successfully.",
      "sendFailed": "Could not send message.",
      "deleteTitle": "Delete message",
      "delete": "Delete",
      "deleteFailed": "Could not delete message."
    },
    "entityDetail": {
      "code": "Code",
      "email": "Email",
      "phone": "Phone",
      "city": "City",
      "state": "State",
      "status": "Status",
      "created": "Created",
      "approveTitle": "Approve entity",
      "rejectTitle": "Reject entity",
      "rejectPlaceholder": "Reason for rejection (optional)",
      "defaultReject": "Rejected from mobile app",
      "approvedMsg": "Entity approved successfully.",
      "rejectedMsg": "Entity rejected.",
      "activate": "Activate",
      "deactivate": "Deactivate",
      "deactivateTitle": "Deactivate entity",
      "activatedMsg": "Entity activated.",
      "deactivatedMsg": "Entity deactivated.",
      "actionFailed": "Action failed."
    },
    "entityRegister": {
      "name": "Entity name",
      "code": "Code",
      "email": "Email",
      "phone": "Phone",
      "city": "City",
      "state": "State",
      "submit": "Register",
      "nameRequired": "Entity name is required.",
      "successTitle": "Registered",
      "successMessage": "Entity registration submitted for approval.",
      "failed": "Registration failed."
    },
    "menu": {
      "title": "Menu Management",
      "subtitle": "Toggle dashboard menu visibility",
      "noData": "No menus found."
    },
    "devMenu": {
      "title": "Developer menu",
      "subtitle": "Open any screen directly."
    }
  }
};
