/**
 * UI Content Dictionary — HI
 * Source of truth for control names, labels, and other UI text shown to users,
 * shared between sms-web and the mobile apps. Namespaced by surface ("web"/"app")
 * because the two products have different screens, not just different languages.
 *
 * DO NOT hand-edit generated sections without updating the source locale files this
 * was generated from (sms-web/src/locales, apps/kuntalstechfie-app/src/i18n/locales)
 * to keep them in sync, or intentionally diverge and note why.
 */
import { UiContentDictionary } from './content.types';

export const UI_CONTENT_HI: UiContentDictionary = {
  "web": {
    "common": {
      "submit": "जमा करें",
      "cancel": "रद्द करें",
      "save": "सहेजें",
      "delete": "हटाएं",
      "edit": "संपादित करें",
      "view": "देखें",
      "search": "खोजें",
      "filter": "फ़िल्टर",
      "close": "बंद करें",
      "back": "वापस",
      "next": "अगला",
      "previous": "पिछला",
      "continue": "जारी रखें",
      "confirm": "पुष्टि करें",
      "loading": "लोड हो रहा है...",
      "noData": "कोई डेटा उपलब्ध नहीं",
      "actions": "कार्रवाई",
      "status": "स्थिति",
      "active": "सक्रिय",
      "inactive": "निष्क्रिय",
      "select": "चुनें",
      "all": "सभी",
      "none": "कोई नहीं",
      "yes": "हां",
      "no": "नहीं"
    },
    "auth": {
      "login": "लॉगिन",
      "signIn": "साइन इन करें",
      "signingIn": "साइन इन हो रहा है...",
      "signOut": "लॉगआउट",
      "logout": "लॉगआउट",
      "username": "उपयोगकर्ता नाम",
      "password": "पासवर्ड",
      "confirmPassword": "पासवर्ड पुष्टि करें",
      "forgotPassword": "पासवर्ड भूल गए?",
      "rememberMe": "मुझे याद रखें",
      "signInToAccount": "अपने खाते में साइन इन करें",
      "enterUsername": "अपना उपयोगकर्ता नाम दर्ज करें",
      "enterPassword": "अपना पासवर्ड दर्ज करें",
      "invalidCredentials": "अमान्य उपयोगकर्ता नाम या पासवर्ड",
      "loginFailed": "लॉगइन विफल",
      "loginSuccess": "सफलतापूर्वक लॉगिन",
      "connectionError": "एक त्रुटि हुई। कृपया अपना कनेक्शन जांचें और पुनः प्रयास करें।",
      "dontHaveAccount": "खाता नहीं है?",
      "registerCompany": "अपनी कंपनी पंजीकृत करें",
      "registerEntity": "स्कूल/ट्यूशन/प्रोग्राम पंजीकृत करें",
      "enrollProgram": "एक प्रोग्राम में नामांकन करें",
      "loginInstruction": "अपने पंजीकृत क्रेडेंशियल के साथ लॉगिन करें या ऊपर एक नया खाता पंजीकृत करें।",
      "selectAccount": "एक खाता चुनें",
      "chooseAccount": "चुनें कि आप किस खाते तक पहुंचना चाहते हैं",
      "selectRole": "भूमिका चुनें",
      "chooseRole": "इस सत्र के लिए अपनी भूमिका चुनें",
      "availableAccounts": "उपलब्ध खाते",
      "availableRoles": "उपलब्ध भूमिकाएं",
      "backToAccountSelection": "खाता चयन पर वापस जाएं",
      "signedInAs": "के रूप में साइन इन किया गया",
      "accountType": {
        "school": "स्कूल",
        "learning": "सीखना"
      },
      "roles": {
        "admin": "व्यवस्थापक",
        "teacher": "शिक्षक",
        "student": "छात्र",
        "parent": "अभिभावक",
        "security": "सुरक्षा"
      }
    },
    "navigation": {
      "dashboard": "डैशबोर्ड",
      "students": "छात्र",
      "staff": "कर्मचारी",
      "parents": "अभिभावक",
      "attendance": "उपस्थिति",
      "fees": "शुल्क",
      "tasks": "कार्य",
      "documents": "दस्तावेज़",
      "notifications": "सूचनाएं",
      "settings": "सेटिंग्स",
      "history": "इतिहास",
      "results": "परिणाम",
      "messages": "संदेश",
      "calendar": "कैलेंडर",
      "busTracking": "बस ट्रैकिंग",
      "profile": "प्रोफाइल",
      "security": "सुरक्षा",
      "language": "भाषा"
    },
    "dashboard": {
      "welcome": "स्वागत है",
      "overview": "अवलोकन",
      "statistics": "आंकड़े",
      "recentActivity": "हाल की गतिविधि",
      "quickActions": "त्वरित कार्य",
      "totalStudents": "कुल छात्र",
      "activeTeachers": "सक्रिय शिक्षक",
      "monthlyRevenue": "मासिक राजस्व",
      "attendanceRate": "उपस्थिति दर",
      "currentGPA": "वर्तमान GPA",
      "assignmentsDue": "शेष असाइनमेंट",
      "liveClassesToday": "आज के लाइव कक्षाएं",
      "studentsEnrolled": "नामांकित छात्र",
      "pendingApprovals": "लंबित अनुमोदन",
      "activeClasses": "सक्रिय कक्षाएं",
      "revenueThisMonth": "इस महीने की आय"
    },
    "students": {
      "title": "छात्र",
      "addStudent": "छात्र जोड़ें",
      "editStudent": "छात्र संपादित करें",
      "deleteStudent": "छात्र हटाएं",
      "studentDetails": "छात्र विवरण",
      "studentList": "छात्र सूची",
      "name": "नाम",
      "email": "ईमेल",
      "phone": "फोन",
      "admissionNumber": "प्रवेश संख्या",
      "class": "कक्षा",
      "section": "अनुभाग",
      "parentName": "अभिभावक का नाम",
      "parentPhone": "अभिभावक का फोन",
      "address": "पता",
      "dateOfBirth": "जन्म तिथि",
      "gender": "लिंग",
      "bloodGroup": "रक्त समूह",
      "guardianName": "अभिभावक का नाम",
      "guardianPhone": "अभिभावक का फोन"
    },
    "staff": {
      "title": "कर्मचारी",
      "addStaff": "कर्मचारी जोड़ें",
      "editStaff": "कर्मचारी संपादित करें",
      "deleteStaff": "कर्मचारी हटाएं",
      "staffDetails": "कर्मचारी विवरण",
      "staffList": "कर्मचारी सूची",
      "employeeId": "कर्मचारी आईडी",
      "designation": "पदनाम",
      "department": "विभाग",
      "joiningDate": "कार्यभार ग्रहण तिथि",
      "qualification": "योग्यता",
      "experience": "अनुभव",
      "salary": "वेतन"
    },
    "attendance": {
      "title": "उपस्थिति",
      "markAttendance": "उपस्थिति दर्ज करें",
      "present": "उपस्थित",
      "absent": "अनुपस्थित",
      "late": "देर से",
      "excused": "माफ",
      "attendanceDate": "तारीख",
      "totalStudents": "कुल छात्र",
      "presentCount": "उपस्थित",
      "absentCount": "अनुपस्थित",
      "attendancePercentage": "उपस्थिति %",
      "attendanceReport": "उपस्थिति रिपोर्ट",
      "monthlyReport": "मासिक रिपोर्ट",
      "exportReport": "रिपोर्ट निर्यात करें"
    },
    "fees": {
      "title": "शुल्क",
      "collectFees": "शुल्क एकत्र करें",
      "pendingFees": "लंबित शुल्क",
      "paidFees": "भुगतान किया गया शुल्क",
      "totalFees": "कुल शुल्क",
      "amountPaid": "भुगतान की गई राशि",
      "balance": "शेष",
      "dueDate": "नियत तारीख",
      "paymentDate": "भुगतान तारीख",
      "receiptNumber": "रसीद संख्या",
      "paymentMode": "भुगतान का तरीका",
      "transactionId": "लेनदेन आईडी"
    },
    "tasks": {
      "title": "कार्य",
      "addTask": "कार्य जोड़ें",
      "editTask": "कार्य संपादित करें",
      "deleteTask": "कार्य हटाएं",
      "taskList": "कार्य सूची",
      "taskTitle": "शीर्षक",
      "description": "विवरण",
      "priority": "प्राथमिकता",
      "status": "स्थिति",
      "dueDate": "नियत तारीख",
      "assignedTo": "सौंपा गया",
      "createdBy": "द्वारा बनाया गया",
      "high": "उच्च",
      "medium": "मध्यम",
      "low": "कम",
      "pending": "लंबित",
      "inProgress": "प्रगति में",
      "completed": "पूर्ण"
    },
    "notifications": {
      "title": "सूचनाएं",
      "markAllRead": "सभी को पढ़ा हुआ चिह्नित करें",
      "noNotifications": "कोई सूचना नहीं",
      "newNotification": "नई सूचना",
      "notificationType": "प्रकार",
      "notificationMessage": "संदेश",
      "notificationTime": "समय",
      "markAsRead": "पढ़ा हुआ चिह्नित करें"
    },
    "settings": {
      "title": "सेटिंग्स",
      "profile": "प्रोफाइल",
      "accountSettings": "खाता सेटिंग्स",
      "changePassword": "पासवर्ड बदलें",
      "currentPassword": "वर्तमान पासवर्ड",
      "newPassword": "नया पासवर्ड",
      "confirmNewPassword": "नया पासवर्ड पुष्टि करें",
      "personalInfo": "व्यक्तिगत जानकारी",
      "contactInfo": "संपर्क जानकारी",
      "preferences": "वरीयताएं",
      "language": "भाषा",
      "theme": "थीम",
      "notifications": "सूचनाएं",
      "emailNotifications": "ईमेल सूचनाएं",
      "pushNotifications": "पुश सूचनाएं"
    },
    "errors": {
      "required": "यह फ़ील्ड आवश्यक है",
      "invalidEmail": "अमान्य ईमेल पता",
      "invalidPhone": "अमान्य फोन नंबर",
      "passwordMismatch": "पासवर्ड मेल नहीं खा रहे",
      "passwordTooShort": "पासवर्ड कम से कम 8 अक्षर का होना चाहिए",
      "somethingWentWrong": "कुछ गलत हो गया। कृपया पुनः प्रयास करें।",
      "networkError": "नेटवर्क त्रुटि। कृपया अपना कनेक्शन जांचें।",
      "unauthorized": "अनधिकृत पहुंच",
      "forbidden": "पहुंच निषिद्ध",
      "notFound": "पृष्ठ नहीं मिला",
      "serverError": "सर्वर त्रुटि। कृपया बाद में पुनः प्रयास करें।"
    },
    "roles": {
      "adminDescription": "स्कूल संचालन, कर्मचारी और छात्रों का प्रबंधन करें",
      "teacherDescription": "कक्षाओं, असाइनमेंट और छात्र प्रगति का प्रबंधन करें",
      "studentDescription": "पाठ्यक्रम, असाइनमेंट और ग्रेड तक पहुंचें",
      "parentDescription": "बच्चों की प्रगति और स्कूल की गतिविधियों की निगरानी करें",
      "securityDescription": "परिसर सुरक्षा और बस ट्रैकिंग का प्रबंधन करें"
    }
  },
  "app": {
    "app": {
      "shortName": "SMS कंपनी"
    },
    "splash": {
      "rolePill": "कंपनी",
      "headlineLine1": "अपना नेटवर्क प्रबंधित करें,",
      "headlineLine2": "एक जगह से।",
      "tagline": "संगठन, टीम, कार्य और सदस्यता — कंपनी एडमिन के लिए।",
      "versionSuffix": "v1.0"
    },
    "languages": {
      "en": "English",
      "hi": "हिन्दी",
      "es": "Español",
      "choose": "भाषा"
    },
    "common": {
      "loading": "लोड हो रहा है...",
      "error": "एक त्रुटि हुई",
      "back": "वापस",
      "viewAll": "सभी देखें",
      "open": "खोलें",
      "active": "सक्रिय",
      "inactive": "निष्क्रिय",
      "pending": "लंबित",
      "approved": "स्वीकृत",
      "rejected": "अस्वीकृत"
    },
    "login": {
      "welcome": "वापस स्वागत है",
      "subtitle": "अपने कंपनी खाते में साइन इन करें",
      "brandTagline": "कंपनी प्रबंधन, सरल बनाया।",
      "devMenu": "डेवलपर मेनू",
      "emailPlaceholder": "ईमेल या उपयोगकर्ता नाम",
      "passwordPlaceholder": "पासवर्ड",
      "forgotPassword": "पासवर्ड भूल गए?",
      "loginButton": "लॉग इन करें",
      "newHere": "नए हैं?",
      "registerCompany": "अपनी कंपनी पंजीकृत करें"
    },
    "errors": {
      "usernameRequired": "कृपया अपना उपयोगकर्ता नाम या ईमेल दर्ज करें।",
      "passwordRequired": "कृपया अपना पासवर्ड दर्ज करें।",
      "loginFailed": "लॉगिन विफल",
      "loginInvalid": "अमान्य उपयोगकर्ता नाम या पासवर्ड।"
    },
    "changePassword": {
      "title": "पासवर्ड बदलें",
      "description": "अपना वर्तमान पासवर्ड और नया सुरक्षित पासवर्ड दर्ज करें।",
      "currentPassword": "वर्तमान पासवर्ड",
      "newPassword": "नया पासवर्ड",
      "confirmPassword": "नया पासवर्ड पुष्टि करें",
      "button": "पासवर्ड अपडेट करें"
    },
    "dashboard": {
      "welcome": "स्वागत",
      "roleLabel": "कंपनी एडमिन",
      "home": "होम",
      "profile": "प्रोफ़ाइल",
      "modules": "मॉड्यूल",
      "today": "आज",
      "greetMorning": "सुप्रभात",
      "greetAfternoon": "नमस्ते",
      "greetEvening": "शुभ संध्या",
      "daySummaryLabel": "अवलोकन",
      "orgsUnit": "संगठन",
      "tasksSummary": "{{tasks}} · ट्रैक पर रहें",
      "primaryCta": "संगठन देखें",
      "yourShortcuts": "त्वरित पहुँच",
      "toolsHeading": "प्रबंधन उपकरण",
      "openPill": "खोलें",
      "notificationsHint": "सूचनाएँ",
      "passCardTitle": "कंपनी पोर्टल",
      "passCardSub": "नीचे शॉर्टकट दबाएँ",
      "peekCardTitle": "इस महीने",
      "peekCardSub": "कार्य और अनुमोदन ट्रैक करें",
      "personalInfo": "व्यक्तिगत जानकारी",
      "accountInfo": "खाता",
      "labelName": "नाम",
      "labelEmail": "ईमेल",
      "labelRole": "भूमिका",
      "notSet": "—",
      "signOut": "साइन आउट",
      "statOrgs": "कुल संगठन",
      "statUsers": "कंपनी उपयोगकर्ता",
      "statTasks": "लंबित कार्य",
      "statApprovals": "लंबित अनुमोदन"
    },
    "modules": {
      "organizations": "संगठन",
      "tasks": "कार्य",
      "teams": "टीमें",
      "users": "उपयोगकर्ता",
      "roleManagement": "भूमिका प्रबंधन",
      "masterData": "मास्टर डेटा",
      "notifications": "सूचनाएँ",
      "settings": "सेटिंग्स",
      "subscription": "सदस्यता",
      "approvals": "अनुमोदन",
      "sales": "बिक्री",
      "operations": "संचालन"
    },
    "moduleDesc": {
      "organizations": "स्कूल, ट्यूशन और कोचिंग",
      "tasks": "लंबित कार्य और अनुवर्ती",
      "teams": "कंपनी टीमें प्रबंधित करें",
      "users": "कंपनी उपयोगकर्ता खाते",
      "roleManagement": "भूमिकाएँ, अनुमतियाँ और RBAC",
      "masterData": "सभी संदर्भ और भौगोलिक डेटा",
      "notifications": "अलर्ट और कंपनी संदेश",
      "settings": "कंपनी प्रोफ़ाइल और कॉन्फ़िगरेशन",
      "subscription": "योजनाएँ, मॉड्यूल और बिलिंग",
      "approvals": "लंबित एंटिटी अनुमोदन",
      "sales": "बिक्री पाइपलाइन",
      "operations": "परिचालन अवलोकन"
    },
    "devMenu": {
      "title": "डेवलपर मेनू",
      "subtitle": "कोई भी स्क्रीन सीधे खोलें।"
    }
  }
};
